apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app
spec:
  selector:
    matchLabels:
      app: django-app
  template:
    metadata:
      labels:
        app: django-app
    spec:
      containers:
      - name: django-app
        image: docker.io/library/django_app:latest
        imagePullPolicy: Never
        envFrom:
        - configMapRef:
            name: django-config
        - secretRef:
            name: django-secret
        ports:
        - containerPort: 80
