apiVersion: v1
kind: Secret
metadata:
  name: django-superuser-secret
type: Opaque
stringData:
  DJANGO_SUPERUSER_EMAIL: admin@example.com
  DJANGO_SUPERUSER_USERNAME: admin
  DJANGO_SUPERUSER_PASSWORD: '123456'
---
apiVersion: batch/v1
kind: Job
metadata:
  name: createsuperuser
spec:
  ttlSecondsAfterFinished: 10
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: django-app
        image: alexwoif/django-app:latest
        env:
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: postgres
                key: dsn
        envFrom:
        - secretRef:
            name: django-secret
        - secretRef:
            name: django-superuser-secret
        command: ['python', 'manage.py', 'createsuperuser', '--noinput']
