apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
  labels:
    app: ubuntu
spec:
  containers:
  - name: ubuntu
    image: ubuntu:20.04
    command:
      - "sleep"
      - "604800"
    envFrom:
    # - configMapRef:
    #     name: django-config
    - secretRef:
        name: postgres
    volumeMounts:
    - name: yandex-root-ca-crt-vol
      mountPath: /root/.postgresql/
  volumes:
  - name: yandex-root-ca-crt-vol
    secret:
      secretName: yandex-root-ca-crt-secret
      defaultMode: 384