apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
  labels:
    app: ubuntu
spec:
  containers:
  - name: ubuntu
    image: ubuntu:20.04
    command:
      - "sleep"
      - "604800"
    envFrom:
    # - configMapRef:
    #     name: django-config
    - secretRef:
        name: postgres

