apiVersion: batch/v1
kind: CronJob
metadata:
  name: django-clearsessions
spec:
  schedule: "* * * * *"
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 1
  startingDeadlineSeconds: 30
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 100
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: django-app
            image: docker.io/library/django_app:latest
            imagePullPolicy: Never
            envFrom:
              - configMapRef:
                  name: django-config
            command: ['python', 'manage.py', 'clearsessions']
