apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app
spec:
  selector:
    matchLabels:
      app: django-app
  template:
    metadata:
      labels:
        app: django-app
    spec:
      containers:
      - name: django-app
        image: docker.io/library/jango_app:latest
        imagePullPolicy: Never
        envFrom:
          - configMapRef:
              name: django-config
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata: 
  name: django-app
spec:
  selector:
    app: django-app
  ports:
    - port: 80
      targetPort: 80
  type: NodePort