apiVersion: v1
kind: ConfigMap
metadata:
  name: django-config
data:
  DEBUG: your_value
  ALLOWED_HOSTS: your_value
---
apiVersion: v1
kind: Secret
metadata:
  name: django-secret
type: Opaque
stringData:
  SECRET_KEY: your_value
  DATABASE_URL: your_value
